version: '3'

networks:
  laravel:

volumes:
  dbdata:
    driver: local

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
      args:
        - UID=${UID:-1003}
        - GID=${GID:-1002}
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - fpm
    networks:
      - laravel


  fpm:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: fpm
    user: "github"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - laravel


  composer:
    container_name: composer
    image: composer
    command: /bin/bash "/app/commands/development/start-composer.sh"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

